runtime: java17
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

beta_settings:
  cloud_sql_instances: <YOUR_CLOUD_SQL_INSTANCE_CONNECTION_NAME>
