global:
  scrape_interval: 15s

scrape_configs:
  # Scraping metrics from the Java Spring Boot app
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['javaapp:8080']

  # Scraping metrics from EMQX (MQTT broker)
  - job_name: 'emqx'
    static_configs:
      - targets: ['emqx_broker:8080']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
